name: Release Workflow

on:
  push:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    env:
      EAS_AUTH_TOKEN: ${{ secrets.EXPO_TOKEN }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'
      
      - name: Install dependencies
        run: yarn install
      
      - name: Install EAS CLI
        run: npm install -g eas-cli
      
      - name: Build iOS Simulator
        run: eas build --platform ios --profile preview --non-interactive